### ISSUE TITLE
Where is it ?

### ISSUE THREAD

**Issue by stephcayrol** [sebastianha/sfoa#6]
Hello, thank you for this smart plugin.
I cannot find the .ics file I downloaded after clicking on the right button. Where is it located ? There is no /var folder neither /tmp on my Mac (10.13.6).

**Comment by sebastianha** [comment]
Hi,
it should be in your tmp folder, but I cannot say for sure where this is located with macOS. With Linux it's /tmp/.

**Comment by sebastianha** [comment]
After downloading the ICS there should open a popup with the download path. There you will find the ICS file.
![Screenshot_20190615_171438](https://user-images.githubusercontent.com/420807/59553142-18c36800-8f91-11e9-8742-a3e88e85406e.png)

**Comment by stephcayrol** [comment]
Hello Sebastian, thanks for your very quick answer. I see the popup (see screen copy) but I don't have a clue where this /var/ folder is. No match in the searchbox, even in the whole computer :-(

![Capture d’écran 2019-06-15 à 17 15 55](https://user-images.githubusercontent.com/51857867/59553156-46101600-8f91-11e9-8677-4caae9c8fc61.png)

**Comment by sebastianha** [comment]
Uh, that's really a weird folder ^^
You could try to open it with your browser by pasting the path there with "file://" as prefix: file:///var/...
I am no mac person but I think it should also be possible to access this folder with the finder app.

**Comment by stephcayrol** [comment]
That's brilliant. The browser doesn't show where it's located, but it reads the file and shows the content. What should I do now with this code ? (I'm a Google Calendar user)

**Comment by sebastianha** [comment]
I only can guess, but this should work when you save the ICS file somewhere: https://support.google.com/calendar/answer/37118?hl=en

**Comment by stephcayrol** [comment]
It works perfectly well, thank you very much.
I copy the path+namefile in the browser, save named .ics, at this point I can already read it in the Apple Calendar app. I can also import it into Google Calendar.

**Comment by sebastianha** [comment]
Perfect! Closing this ticket.
